# INTENTIONALLY VULNERABLE LAB CONFIGURATION.

<Directory /var/www/html/archives>
    Require all granted
    IndexOptions FancyIndexing NameWidth=* DescriptionWidth=*
    Options +Indexes
</Directory>

<Directory /var/www/html>
    AllowOverride All
    Require all granted
    Options +Indexes
</Directory>